/**
 * Theme colors based on Tailwind v4 design system
 * Colors are converted from OKLCH to hex for React Native compatibility
 */

// Light theme colors
const light = {
  background: "#f7f7f9",
  foreground: "#4a4a6a",
  card: "#ffffff",
  cardForeground: "#4a4a6a",
  popover: "#ffffff",
  popoverForeground: "#4a4a6a",
  primary: "#5947e1",
  primaryForeground: "#ffffff",
  secondary: "#eaeaf0",
  secondaryForeground: "#6a6a8a",
  muted: "#f5f5f7",
  mutedForeground: "#8a8a9a",
  accent: "#eaeaf0",
  accentForeground: "#4a4a6a",
  destructive: "#e11d48",
  destructiveForeground: "#ffffff",
  border: "#e8e8f0",
  input: "#e8e8f0",
  ring: "#5947e1",
  chart1: "#5947e1",
  chart2: "#8a7ae1",
  chart3: "#7a6ae1",
  chart4: "#9a8ae1",
  chart5: "#6a5ae1",
  sidebar: "#f5f5f7",
  sidebarForeground: "#4a4a6a",
  sidebarPrimary: "#5947e1",
  sidebarPrimaryForeground: "#ffffff",
  sidebarAccent: "#eaeaf0",
  sidebarAccentForeground: "#4a4a6a",
  sidebarBorder: "#e8e8f0",
  sidebarRing: "#5947e1",
  divider: "#e8e8f0",
  dividerStrong: "#d8d8e0",
  dividerWeak: "#f0f0f5",
  sectionBackground: "#f0f2ff",
  sectionBorder: "#e8e8f0",
};

// Dark theme colors
const dark = {
  background: "#2a2a3a",
  foreground: "#eaeaf0",
  card: "#3a3a4a",
  cardForeground: "#eaeaf0",
  popover: "#3a3a4a",
  popoverForeground: "#eaeaf0",
  primary: "#cba6f7",
  primaryForeground: "#2a2a3a",
  secondary: "#4a4a5a",
  secondaryForeground: "#dadae0",
  muted: "#3a3a4a",
  mutedForeground: "#baba9a",
  accent: "#4a4a5a",
  accentForeground: "#eaeaf0",
  destructive: "#e11d48",
  destructiveForeground: "#ffffff",
  border: "#4a4a5a",
  input: "#4a4a5a",
  ring: "#cba6f7",
  chart1: "#cba6f7",
  chart2: "#a6b6f7",
  chart3: "#a6c6f7",
  chart4: "#a6d6f7",
  chart5: "#f7a6a6",
  sidebar: "#3a3a4a",
  sidebarForeground: "#eaeaf0",
  sidebarPrimary: "#cba6f7",
  sidebarPrimaryForeground: "#2a2a3a",
  sidebarAccent: "#4a4a5a",
  sidebarAccentForeground: "#eaeaf0",
  sidebarBorder: "#4a4a5a",
  sidebarRing: "#cba6f7",
  divider: "#4a4a5a",
  dividerStrong: "#5a5a6a",
  dividerWeak: "#3a3a4a",
  sectionBackground: "#3a3a4a",
  sectionBorder: "#4a4a5a",
};

export const COLORS = {
  light,
  dark,
};
